### PR TITLE
Adding signature

### PR DESCRIPTION
**Pull request by Mikaelsu**
I updated the security config and merged it, but @mcollovati pointed out an addition when I updated the docs. See related [docs PR](https://github.com/vaadin/docs/pull/2652)

### CODE REVIEW

**Comment by mcollovati** [comment]
It would be good to upgrade Spring Boot to the latest version (3.1.2)

**Comment by Mikaelsu** [comment]
> It would be good to upgrade Spring Boot to the latest version (3.1.2)

Good idea, updated.

**Comment by mcollovati** [comment]
Do you want to apply also the change suggested by knoobie?
```
AntPathRequestMatcher.antMatcher(HttpMethod.GET, "/images/*.png")
```

**Comment by Mikaelsu** [comment]
> Do you want to apply also the change suggested by knoobie?
> 
> ```
> AntPathRequestMatcher.antMatcher(HttpMethod.GET, "/images/*.png")
> ```
Let's do that. Sorry i'm multitasking, pushing a commit in 3, 2, 1...

**Review by mcollovati — APPROVED** [review]
Looks good.
Spring Boot updated and tests are green both locally and on the CI server

**Pull request merged**
